-- Seed products table from static product catalog.
-- Safe to re-run: ON CONFLICT updates price/status/name.
-- status='published' → visible to checkout; status='published' → checkout rejects.

insert into public.products (slug, name, description, price_cents, image_url, category, is_active, featured, status, sizes)
values
  (
    'im-your-favorite-bartenders-favorite-bartender-tee',
    'I''m Your Favorite Bartender''s Favorite Bartender',
    'Let your guests know that you''re the property value of this establishment and your coworkers are only here as supporting cast.',
    2799,
    '/products/im-your-favorite-bartenders-favorite-bartender-tee-0.png',
    'industry-truths',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'i-would-totally-tap-that-keg-tee',
    'I Would Totally Tap That - Keg',
    'However, be careful when tapping. It might spray!',
    2799,
    '/products/i-would-totally-tap-that-keg-tee-0.png',
    'industry-truths',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'saving-my-bar-from-the-socially-stupid-one-karen-at-a-time-tee',
    'Saving My Bar From the Socially Stupid, One Karen at a Time',
    'Karens create Karens. And we need to put a stop to it!',
    2799,
    '/products/saving-my-bar-from-the-socially-stupid-one-karen-at-a-time-tee-0.png',
    'customer-horror',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'pournogravy-og-tee-the-official-uniform-for-bartender-legends',
    'Pournogravy Logo Tee',
    'Rep the brand that''s repping you!',
    2799,
    '/products/pournogravy-og-tee-the-official-uniform-for-bartender-legends-0.png',
    'industry-truths',
    true,
    true,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'last-call-for-karen-tee',
    'Last Call for Karen',
    'This design signifies that you are part of the movement to end the Post-Pandemic Karen Entitlement Act.',
    2799,
    '/products/last-call-for-karen-tee-0.png',
    'customer-horror',
    true,
    true,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'service-bartender-do-not-approach-tee',
    'Service Bartender, Do Not Approach',
    'For bartenders running service bar — no small talk, no phone charging.',
    2799,
    '/products/service-bartender-do-not-approach-tee-0.png',
    'salty-bartender',
    true,
    true,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'atheist-tee',
    'You Cannot Be an Atheist if You Believe in Bartenders',
    'They come in and confuse us for a higher power.',
    2799,
    '/products/atheist-tee-0.png',
    'salty-bartender',
    true,
    true,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'atheist-with-text-only',
    'You Cannot Be an Atheist if You Believe in Bartenders (Text)',
    'They come in and confuse us for a higher power.',
    2799,
    '/products/atheist-with-text-only-0.png',
    'salty-bartender',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'the-finger-tee',
    'The Finger',
    'This shirt is for bartenders who put the "B" in "subtle".',
    2799,
    '/products/the-finger-tee-0.png',
    'industry-truths',
    true,
    true,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'pourn-hand-tee',
    'Pourn Hand',
    'For the bartender who pours in a little love.',
    2799,
    '/products/pourn-hand-tee-0.png',
    'salty-bartender',
    true,
    true,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'second-most-fun-job-tee',
    'Second Most Fun Job in the World',
    'Which of history''s oldest professions is better?',
    2799,
    '/products/second-most-fun-job-tee-0.png',
    'industry-truths',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'introverted-bartender-tee',
    'Introverted Bartender',
    'For the bartender that loves the job but hates the public.',
    2799,
    '/products/introverted-bartender-tee-0.jpg',
    'industry-truths',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'legally-fun-tee-text-only',
    'Second Most Fun Job in the World (Text)',
    'Which of history''s oldest professions is better?',
    2799,
    '/products/legally-fun-tee-text-only-0.png',
    'industry-truths',
    true,
    false,
    'published',
    array['S','M','L','XL','2XL','3XL']
  ),
  (
    'tip-your-therapist-tee',
    'Tip Your Therapist',
    'Tipping is cheaper than the cost of therapy.',
    2799,
    '/products/tip-your-therapist-tee-0.png',
    'salty-bartender',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'strn-drink-tee-text-and-image',
    'Your Next Drink is Only as Strong as Your Last Tip',
    'Excuse me! I don''t taste any alcohol in my drink!',
    2799,
    '/products/strn-drink-tee-text-and-image-0.png',
    'salty-bartender',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'well-it-ain-t-gonna-lick-itself-tee',
    'Well, It Ain''t Gonna Lick Itself',
    'Make sure to wash and wipe your glass before rimming.',
    2799,
    '/products/well-it-ain-t-gonna-lick-itself-tee-0.png',
    'salty-bartender',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'tea-toes-and-vodka-please-tee',
    'Tea, Toes, and Vodka Please',
    'Let us celebrate this popular libation.',
    2799,
    '/products/tea-toes-and-vodka-please-tee-0.png',
    'salty-bartender',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'dear-karen-you-stink-tee',
    'Dear Karen, You Stink',
    'A politically incorrect way of waving hello to your favorite Karen.',
    2799,
    '/products/dear-karen-you-stink-tee-0.png',
    'customer-horror',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'i-bought-this-real-shirt-with-my-real-money-from-my-real-job-tee-text-only',
    'My Real Job (Text Only)',
    'For any bartender who''s done explaining themselves.',
    2799,
    '/products/i-bought-this-real-shirt-with-my-real-money-from-my-real-job-tee-text-only-0.png',
    'salty-bartender',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'i-bought-this-real-shirt-with-my-real-money-from-my-real-job-tee',
    'My Real Job',
    'For any bartender who''s done explaining themselves.',
    2799,
    '/products/i-bought-this-real-shirt-with-my-real-money-from-my-real-job-tee-0.png',
    'salty-bartender',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'your-next-drink-is-only-as-strong-as-your-last-tip-tee',
    'Your Next Drink is Only as Strong as Your Last Tip (Text)',
    'Excuse me! I don''t taste any alcohol in my drink!',
    2799,
    '/products/your-next-drink-is-only-as-strong-as-your-last-tip-tee-0.png',
    'salty-bartender',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'do-you-like-it-in-a-glass-or-do-you-take-it-in-the-can-tee',
    'Do You Like It in a Glass? Or Do You Take It in the Can?',
    'I always smirk and ask this every time I serve a hard seltzer.',
    2799,
    '/products/do-you-like-it-in-a-glass-or-do-you-take-it-in-the-can-tee-0.png',
    'salty-bartender',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'f-off-karen',
    'F Off Karen',
    'A politically correct way of waving hello to your favorite Karen.',
    2799,
    '/products/f-off-karen-0.png',
    'customer-horror',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  ),
  (
    'cow-tipping',
    'Cow Tipping',
    'This design will remind your guests that you are an udderly amazing bartender.',
    2799,
    '/products/cow-tipping-0.png',
    'customer-horror',
    true,
    false,
    'published',
    array['XS','S','M','L','XL','2XL','3XL']
  )
on conflict (slug) do update set
  name        = excluded.name,
  price_cents = excluded.price_cents,
  is_active   = excluded.is_active,
  status      = excluded.status,
  image_url   = excluded.image_url,
  featured    = excluded.featured,
  category    = excluded.category,
  sizes       = excluded.sizes;
