-- Replace order_confirmation template with bar-tab / guest-check style.
-- Inline CSS only (no external stylesheets — email client compatibility).
-- Variables: customer_name, order_number, order_items, order_subtotal,
--            shipping_cost, order_total, mock_image_url

UPDATE public.email_templates
SET
  subject   = 'Your tab is settled — order {{order_number}}',
  body_html = '<div style="font-family:''Courier New'',Courier,monospace;max-width:520px;margin:0 auto;background:#faf8f0;border:1px solid #d4c5a0;padding:0;color:#1a0e04;"><div style="text-align:center;padding:24px 24px 16px;border-bottom:2px dashed #a08040;"><div style="font-size:22px;font-weight:bold;letter-spacing:0.18em;text-transform:uppercase;">POURnogravy</div><div style="font-size:11px;letter-spacing:0.12em;color:#7a5820;margin-top:3px;">pournogravy.com</div><div style="font-size:18px;font-weight:bold;letter-spacing:0.12em;text-transform:uppercase;margin-top:14px;line-height:1.3;">THANKS FOR DRINKING<br/>WITH US</div></div><div style="padding:14px 24px 10px;border-bottom:1px dashed #c0a060;font-size:12px;color:#5a3a10;"><div>ORDER #: <strong style="color:#1a0e04;">{{order_number}}</strong></div><div style="margin-top:3px;">TAB FOR: {{customer_name}}</div></div><div style="padding:14px 24px;border-bottom:2px dashed #a08040;"><pre style="font-family:''Courier New'',Courier,monospace;font-size:13px;white-space:pre-wrap;margin:0;color:#1a0e04;line-height:1.7;">{{order_items}}</pre></div><div style="padding:14px 24px;"><table style="width:100%;font-size:13px;border-collapse:collapse;"><tr><td style="padding:3px 0;color:#5a3a10;">SUBTOTAL</td><td style="padding:3px 0;text-align:right;color:#1a0e04;">{{order_subtotal}}</td></tr><tr><td style="padding:3px 0;color:#5a3a10;">SHIPPING</td><td style="padding:3px 0;text-align:right;color:#1a0e04;">{{shipping_cost}}</td></tr><tr style="border-top:2px solid #1a0e04;"><td style="padding:6px 0 3px;font-weight:bold;font-size:15px;">TOTAL</td><td style="padding:6px 0 3px;text-align:right;font-weight:bold;font-size:15px;">{{order_total}}</td></tr></table></div><div style="text-align:center;padding:16px 24px 24px;border-top:2px dashed #a08040;"><div style="font-size:13px;font-weight:bold;letter-spacing:0.12em;text-transform:uppercase;color:#1a0e04;">NOW GO WEAR IT TO THE BAR<br/>AND START TROUBLE.</div><div style="font-size:11px;color:#9a7050;margin-top:10px;">Questions? Just reply to this email.</div></div></div>',
  body_text = E'POURnogravy — THANKS FOR DRINKING WITH US\n\nOrder #: {{order_number}}\nTab for: {{customer_name}}\n\n---\n{{order_items}}\n---\n\nSubtotal:  {{order_subtotal}}\nShipping:  {{shipping_cost}}\nTOTAL:     {{order_total}}\n\nNOW GO WEAR IT TO THE BAR AND START TROUBLE.\n\nQuestions? Reply to this email.\npournogravy.com',
  variables = ARRAY['customer_name','order_number','order_items','order_subtotal','shipping_cost','order_total','mock_image_url']
WHERE key = 'order_confirmation';
